create extension if not exists pgcrypto;
create table if not exists public.files (
 id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text, category text not null default 'Other', mime_type text not null default 'external/link', size_bytes bigint not null default 0, storage_path text unique, external_url text, thumbnail_url text, tags text[] not null default '{}', version text, downloads bigint not null default 0, is_public boolean not null default true, created_at timestamptz not null default now()
);
alter table public.files add column if not exists external_url text;
alter table public.files alter column storage_path drop not null;
alter table public.files enable row level security;
create policy "public can read public files" on public.files for select using (is_public=true);
create or replace function public.increment_downloads(file_id uuid) returns void language sql security definer as $$ update public.files set downloads=downloads+1 where id=file_id; $$;
create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  event_type text not null check (event_type in ('visit', 'download')),
  video_url text,
  device text not null default 'Unknown',
  browser text not null default 'Unknown',
  country text not null default 'Unknown',
  city text not null default 'Unknown',
  created_at timestamptz not null default now()
);
create index if not exists visitor_events_created_at_idx on public.visitor_events (created_at desc);
alter table public.visitor_events enable row level security;
-- Create a private Storage bucket named `files` in Supabase Storage.
-- Recommended Storage policy: allow authenticated admins to INSERT/UPDATE/DELETE; signed URLs are generated server-side.
